[versions]
dataprovider = "2.10"
# must be changed together
junit5 = "6.0.2"
junit5_platform = "6.0.2"

[libraries]
apache_commons = { group = "org.apache.commons", name = "commons-lang3", version = "3.20.0" }
guava = { group = "com.google.guava", name = "guava", version = "33.5.0-jre" }
slf4j_api = { group = "org.slf4j", name = "slf4j-api", version = "2.0.17" }
lombok = { group = "org.projectlombok", name = "lombok", version = "1.18.42" }

junit4 = { group = "junit", name = "junit", version = "4.13.2" }
junit4_dataprovider = { group = "com.tngtech.junit.dataprovider", name = "junit4-dataprovider", version.ref = "dataprovider" }
junit5_dataprovider = { group = "com.tngtech.junit.dataprovider", name = "junit-jupiter-dataprovider", version.ref = "dataprovider" }
assertj_core = { group = "org.assertj", name = "assertj-core", version = "3.27.6" }
slf4j_simple = { group = "org.slf4j", name = "slf4j-simple", version = "2.0.17" }

junit4_engine = { group = "org.junit.vintage", name = "junit-vintage-engine", version.ref = "junit5" }
junit_jupiter_api = { group = "org.junit.jupiter", name = "junit-jupiter-api", version.ref = "junit5" }
junit_jupiter_engine = { group = "org.junit.jupiter", name = "junit-jupiter-engine", version.ref = "junit5" }
junit_jupiter_params = { group = "org.junit.jupiter", name = "junit-jupiter-params", version.ref = "junit5" }
junit_jupiter_testkit = { group = "org.junit.platform", name = "junit-platform-testkit", version.ref = "junit5_platform" }
junit_platform_launcher = { group = "org.junit.platform", name = "junit-platform-launcher", version.ref = "junit5_platform" }
